apiVersion: v1
kind: Service
metadata:
  name: emby-server-lb
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
spec:
  type: LoadBalancer
  selector:
    app: emby-server
  ports:
    - name: http
      port: 8096
      targetPort: 8096
